substitutions:
  device_name: "small-controller"
  encryptionkey: ""
  otapass: ""
  appass: ""

esphome:
  name: "$device_name"
  includes:
    - custom_components/lc709203f/lc709203f.h
  libraries:
    - i2c

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: arduino
    version: 2.0.6
    platform_version: 5.1.0
  variant: esp32s3

i2c:
  sda: 3
  scl: 4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "${encryptionkey}"

ota:
  password: "${otapass}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: "${appass}"

captive_portal:
bluetooth_proxy:

light:
 - platform: status_led
   pin: GPIO13
   name: "SC Red Light"
 - platform: fastled_clockless
   rgb_order: GRB
   chipset: WS2812B
   pin: GPIO33
   num_leds: 1
   name: "SC NeoPixel LED"
   id: sc_neopixel_led
 - platform: fastled_clockless
   rgb_order: GRB
   chipset: WS2812B
   pin: GPIO05
   num_leds: 9
   name: "SC NeoPixel LED Grid"
 - platform: fastled_clockless
   rgb_order: GRB
   chipset: WS2812B
   pin: GPIO13
   num_leds: 5
   name: "SC NeoPixel Base"

output:
  - platform: gpio
    pin: GPIO21
    id: neopixelpower
    inverted: true

matrix_keypad:
  id: mykeypad
  columns:
    - pin: 15
    - pin: 14
    - pin: 36
  rows: 
    - pin: 18
    - pin: 17
    - pin: 16
  #has_diodes: true
  keys: "012345678"

binary_sensor:
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: SmallA
    key: 0
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallB"
    key: 1
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallC"
    key: 2
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallD"
    key: 3
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallE"
    key: 4
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallF"
    key: 5
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallG"
    key: 6
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallH"
    key: 7
  - platform: matrix_keypad
    keypad_id: mykeypad
    name: "SmallI"
    key: 8

sensor:
  - platform: lc709203f
    address: 0x0B
    battery_level:
      name: "Small Controller battery level"
    cell_charge:
      name: "Small Controller cell charge"
    update_interval: 30s
